package com.piglatin.piglatin.domain.ast.visitor;

import com.piglatin.piglatin.domain.ast.nodes.*;
import com.piglatin.piglatin.domain.ast.nodes.NodeImport;
import com.piglatin.piglatin.domain.ast.nodes.declaration.*;
import com.piglatin.piglatin.domain.ast.nodes.lvalue.*;
import com.piglatin.piglatin.domain.ast.nodes.expression.*;
import com.piglatin.piglatin.domain.ast.nodes.instruction.*;
import com.piglatin.piglatin.domain.ast.nodes.literal.*;
import com.piglatin.piglatin.domain.ast.principal.ASTNode;
import com.piglatin.piglatin.domain.ast.principal.NodeProgram;
import com.piglatin.piglatin.infrastructure.parser.generated.LatinParser;
import com.piglatin.piglatin.infrastructure.parser.generated.LatinParserBaseVisitor;
import org.antlr.v4.runtime.tree.TerminalNode;

import java.util.ArrayList;
import java.util.List;

/**
 * ANTLR4 Visitor -> Custom AST.
 * Converts the Concrete Syntax Tree (CST) generated by ANTLR4 into the
 * Abstract Syntax Tree (AST) defined in package model.nodes.
 *
 * Each visit Context method takes a CST node and returns the equivalent AST
 * node
 */
public class ASTBuilder extends LatinParserBaseVisitor<ASTNode> {

    //* ============================================================
    //* ROOT PROGRAM
    //* ============================================================

    @Override
    public ASTNode visitProgram(LatinParser.ProgramContext ctx) {
        NodeProgram program = new NodeProgram();

        //* Imports
        if (ctx.importList() != null) {
              ASTNode imports = visit(ctx.importList());
              if (imports != null) program.setImports((List<NodeImport>) imports);
        }

        //* Global declarations
        if (ctx.globalDeclarations() != null) {
            for (LatinParser.GlobalDeclarationContext declCtx : ctx.globalDeclarations().globalDeclaration()) {
                ASTNode decl = visit(declCtx);
                if (decl instanceof NodeDeclaration) {
                    program.addGlobalDeclaration((NodeDeclaration) decl);
                }
            }
        }

        //* Main instructions
        if (ctx.mainInstructions() != null) {
            for (LatinParser.InstructionContext instCtx : ctx.mainInstructions().instruction()) {
                ASTNode inst = visit(instCtx);
                if (inst != null) {
                    program.addMainInstruction(inst);
                }
            }
        }

        return program;
    }

    @Override
    public ASTNode visitImportList(LatinParser.ImportListContext ctx){
        List<NodeImport> imports = new ArrayList<>();
        for (LatinParser.ImportStatementContext impCtx : ctx.importStatement()) {
            ASTNode imp = visit(impCtx);
            if (imp instanceof NodeImport) imports.add((NodeImport) imp);
        }
        return (ASTNode) imports;
    }

    @Override
    public ASTNode visitImportStatement(LatinParser.ImportStatementContext ctx) {
        List<String> path = new ArrayList<>();
        for (TerminalNode idCtx : ctx.ID()){
            path.add(idCtx.getText());
        }
        return new NodeImport(path, ctx.getStart().getLine(), ctx.getStart().getCharPositionInLine());
    }

    @Override
    public ASTNode visitGlobalDeclarationVariable (LatinParser.GlobalDeclarationVariableContext ctx){
        return visit(ctx.declaration());
    }

    @Override
    public ASTNode visitGlobalDeclarationArray(LatinParser.GlobalDeclarationArrayContext ctx) {
        return visit(ctx.arrayDeclaration());
    }

    @Override
    public ASTNode visitMainInstructions(LatinParser.MainInstructionsContext ctx) {
        return null;
    }

    // ============================================================
    // STATEMENTS
    // ============================================================

    @Override
    public ASTNode visitDeclaration(LatinParser.DeclarationContext ctx) {
        String id = ctx.ID().getText();
        String type = ctx.type() != null ? extractType(ctx.type()) : null;
        ASTNode initializer = ctx.expression() != null
                ? normalizeInitializerLiteral(
                        visit(ctx.expression()),
                        ctx.expression().getText(),
                        ctx.getStart().getLine(),
                        ctx.getStart().getCharPositionInLine())
                : null;

        return new NodeVariableDeclaration(
                id,
                type,
                initializer,
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine());
    }

    @Override
    public ASTNode visitArrayDeclaration(LatinParser.ArrayDeclarationContext ctx) {
        String id = ctx.ID().getText();
        ASTNode sizeExpr = visit(ctx.expression());
        String elementType = ctx.type() != null ? extractType(ctx.type()) : null;

        NodeArrayDeclaration arrDecl = new NodeArrayDeclaration(
                id,
                sizeExpr,
                elementType,
                new ArrayList<>(),
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine());

        if (ctx.arrayLiteral() != null) {
            ASTNode literal = visit(ctx.arrayLiteral());
            if (literal instanceof NodeArrayLiteral) arrDecl.setInitialValues(((NodeArrayLiteral) literal).getValues());
        }
        return arrDecl;
    }

    // ============================================================
    // INSTRUCTIONS
    // ============================================================

    @Override
    public ASTNode visitInstructionAssignment (LatinParser.InstructionAssignmentContext ctx) {
            return visit(ctx.assignment());
    }

    @Override
    public ASTNode visitInstructionRead (LatinParser.InstructionReadContext ctx) {
        return visit(ctx.readStatement());
    }

    @Override
    public ASTNode visitInstructionPrint (LatinParser.InstructionPrintContext ctx) {
        return visit(ctx.printStatement());
    }

    @Override
    public ASTNode visitInstructionIf (LatinParser.InstructionIfContext ctx) {
        return visit(ctx.ifStatement());
    }

    @Override
    public ASTNode visitInstructionWhile (LatinParser.InstructionWhileContext ctx) {
        return visit(ctx.whileStatement());
    }

    @Override
    public ASTNode visitAssignment(LatinParser.AssignmentContext ctx) {
        NodeLvalue lvalue = asLvalue(visit(ctx.lvalue()));
        ASTNode expression = visit(ctx.expression());
        return new NodeAssignment(
                lvalue,
                expression,
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine());
    }

    @Override
    public ASTNode visitReadSimple(LatinParser.ReadSimpleContext ctx) {
        return new NodeRead(
                null,
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine());
    }

    @Override
    public ASTNode visitPrintStatement(LatinParser.PrintStatementContext ctx) {
        NodePrint print = new NodePrint(
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine());
        for (LatinParser.PrintItemContext itemCtx : ctx.printItem()) {
            ASTNode item = visit(itemCtx);
            if (item != null) {
                print.addPrintItem(item);
            }
        }
        return print;
    }

    @Override
    public ASTNode visitPrintItemString(LatinParser.PrintItemStringContext ctx) {
        return new NodeStringLiteral(
                ctx.STRING().getText(),
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine());
    }

    @Override
    public ASTNode visitPrintItemID(LatinParser.PrintItemIDContext ctx) {
        return new NodeIdentifier(
                ctx.ID().getText(),
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine());
    }

    @Override
    public ASTNode visitPrintItemExpression(LatinParser.PrintItemExpressionContext ctx) {
        return visit(ctx.expression());
    }

    @Override
    public ASTNode visitIfStatement(LatinParser.IfStatementContext ctx) {

        ASTNode condition = visit(ctx.booleanExpression());
        NodeBlock thenBlock = asBlock(visit(ctx.block()));

        NodeIf nodeIf = new NodeIf(
                condition,
                thenBlock,
                new ArrayList<>(),
                null,
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine());

        // * else if clauses
        for (LatinParser.ElseIfClauseContext elseIfCtx : ctx.elseIfClause()) {
            ASTNode elseConditionNode = visit(elseIfCtx.booleanExpression());
            NodeBooleanExpression elseCondition = wrapBoolean(elseConditionNode, elseIfCtx.getStart().getLine(),
                    elseIfCtx.getStart().getCharPositionInLine());
            NodeBlock elseIfBlock = asBlock(visit(elseIfCtx.block()));
            nodeIf.addElseIfClause(elseCondition, elseIfBlock);
        }

        // * else clause
        if (ctx.elseClause() != null) {
            nodeIf.setElseBlock(asBlock(visit(ctx.elseClause())));
        }

        return nodeIf;
    }

    @Override
    public ASTNode visitElseIfClause(LatinParser.ElseIfClauseContext ctx) {
        return null;
    }

    @Override
    public ASTNode visitElseClause(LatinParser.ElseClauseContext ctx) {
        return visit(ctx.block());
    }

    @Override
    public ASTNode visitWhileStatement(LatinParser.WhileStatementContext ctx) {
        ASTNode condition= visit(ctx.booleanExpression());
        NodeBlock block = asBlock(visit(ctx.block()));
        return new NodeWhile(
                condition,
                block,
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine());
    }

    @Override
    public ASTNode visitDoWhileStatement(LatinParser.DoWhileStatementContext ctx) {
        NodeBlock block = asBlock(visit(ctx.block()));
        ASTNode condition = visit(ctx.booleanExpression());
        return new NodeDoWhile(
                block,
                condition,
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine());
    }

    @Override
    public ASTNode visitForStandard(LatinParser.ForStandardContext ctx) {
        ASTNode init = ctx.forInit() != null ? visit(ctx.forInit()) : null;
        ASTNode condition = ctx.forCondition() != null ? visit(ctx.forCondition()) : null;
        ASTNode update = ctx.forUpdate() != null ? visit(ctx.forUpdate()) : null;
        NodeBlock block = asBlock(visit(ctx.block()));

        return new NodeFor(
                init,
                condition,
                update,
                block,
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine());
    }

    @Override
    public ASTNode visitForInitWithDeclaration(LatinParser.ForInitWithDeclarationContext ctx) {
        String id = ctx.ID().getText();
        String type = ctx.type() != null ? extractType(ctx.type()) : null;
        ASTNode initializer = ctx.expression() != null
                ? normalizeInitializerLiteral(
                        visit(ctx.expression()),
                        ctx.expression().getText(),
                        ctx.getStart().getLine(),
                        ctx.getStart().getCharPositionInLine())
                : null;
        return new NodeVariableDeclaration(
                id,
                type,
                initializer,
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine());
    }

    @Override
    public ASTNode visitForInitWithAssign(LatinParser.ForInitWithAssignContext ctx) {
        NodeLvalue lvalue = asLvalue(visit(ctx.lvalue()));
        ASTNode expression = visit(ctx.expression());
        return new NodeAssignment(
                lvalue,
                expression,
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine());
    }

    @Override
    public ASTNode visitForInitWithID(LatinParser.ForInitWithIDContext ctx) {
        return new NodeIdentifier(
                ctx.ID().getText(),
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine());
    }

    @Override
    public ASTNode visitForUpdateExpression(LatinParser.ForUpdateExpressionContext ctx) {
        return visit(ctx.expression());
    }

    @Override
    public ASTNode visitForUpdateLvalue(LatinParser.ForUpdateLvalueContext ctx) {
        NodeLvalue lvalue = asLvalue(visit(ctx.lvalue()));
        ASTNode expression = visit(ctx.expression());
        return new NodeAssignment(
                lvalue,
                expression,
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine());
    }

    @Override
    public ASTNode visitJumpStatementContinue(LatinParser.JumpStatementContinueContext ctx) {
        return new NodeContinue(
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine());
    }

    @Override
    public ASTNode visitJumpStatementReturn(LatinParser.JumpStatementReturnContext ctx) {
        return new NodeBreak(
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine());
    }

    @Override
    public ASTNode visitReturnStatement(LatinParser.ReturnStatementContext ctx) {
        ASTNode expression = ctx.expression() != null ? visit(ctx.expression()) : null;
        return new NodeReturn(
                expression,
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine());
    }

    @Override
    public ASTNode visitBlock(LatinParser.BlockContext ctx) {
        NodeBlock block = new NodeBlock(
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine());
        for (LatinParser.InstructionContext instCtx : ctx.instruction()) {
            ASTNode inst = visit(instCtx);
            if (inst != null) {
                block.addInstruction(inst);
            }
        }
        return block;
    }

    // ============================================================
    // LVALUE assignable values
    // ============================================================

    @Override
    public ASTNode visitLvalue(LatinParser.LvalueContext ctx) {
        NodeLvalue lvalue = new NodeLvalue(
                ctx.ID().getText(),
                new ArrayList<>(),
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine());

        for (LatinParser.LvalueSufixContext suffixCtx : ctx.lvalueSufix()) {
            ASTNode suffix = visit(suffixCtx);
            if (suffix != null) {
                lvalue.addSuffix(suffix);
            }
        }

        return lvalue;
    }

    @Override
    public ASTNode visitFieldAccess(LatinParser.FieldAccessContext ctx) {
        return new NodeFieldAccess(
                ctx.ID().getText(),
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine());
    }

    @Override
    public ASTNode visitIndexAccess(LatinParser.IndexAccessContext ctx) {
        ASTNode index = visit(ctx.expression());
        return new NodeIndexAccess(
                index,
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine());
    }

    // ============================================================
    // GENERAL EXPRESSIONS
    // ============================================================


    @Override
    public ASTNode visitExpressionArrayLiteral(LatinParser.ExpressionArrayLiteralContext ctx) {
        return visit(ctx.arrayLiteral());
    }

    @Override
    public ASTNode visitNumericLiteralChar(LatinParser.NumericLiteralCharContext ctx) {
        String text = ctx.CHAR().getText();
        char value = text.length() >= 3 ? text.charAt(1) : '\0';
        return new NodeIntegerLiteral(
                (int) value,
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine());
    }

    // ============================================================
    // BOOLEAN EXPRESSIONS
    // ============================================================

    @Override
    public ASTNode visitBooleanOrExpression(LatinParser.BooleanOrExpressionContext ctx) {
        List<LatinParser.BooleanAndExpressionContext> operands = ctx.booleanAndExpression();
        ASTNode left = visit(operands.get(0));
        for (int i = 1; i < operands.size(); i++) {
            ASTNode right = visit(operands.get(i));
            left = new NodeBinaryOperation(
                    left,
                    "||",
                    right,
                    ctx.getStart().getLine(),
                    ctx.getStart().getCharPositionInLine());
        }
        return left;
    }

    @Override
    public ASTNode visitBooleanAndExpression(LatinParser.BooleanAndExpressionContext ctx) {
        List<LatinParser.ComparisonExpressionContext> operands = ctx.comparisonExpression();
        ASTNode left = visit(operands.get(0));
        for (int i = 1; i < operands.size(); i++) {
            ASTNode right = visit(operands.get(i));
            left = new NodeBinaryOperation(
                    left,
                    "&&",
                    right,
                    ctx.getStart().getLine(),
                    ctx.getStart().getCharPositionInLine());
        }
        return left;
    }

    @Override
    public ASTNode visitComparisonExpressionNot(LatinParser.ComparisonExpressionNotContext ctx) {
        ASTNode operand = visit(ctx.comparisonExpression());
        return new NodeUnaryOperation(
                "!",
                operand,
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine());
    }

    @Override
    public ASTNode visitComparisonExpressionComparisonOperand(
            LatinParser.ComparisonExpressionComparisonOperandContext ctx) {
        if (ctx.comparisonOperand().size() == 1) {
            return visit(ctx.comparisonOperand(0));
        }
        ASTNode left = visit(ctx.comparisonOperand(0));
        ASTNode right = visit(ctx.comparisonOperand(1));
        String operator = extractRelationalOperator(ctx.relationalLiteral());
        return new NodeBinaryOperation(
                left,
                operator,
                right,
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine());
    }

    @Override
    public ASTNode visitComparisonExpressionBooleanExpresion(
            LatinParser.ComparisonExpressionBooleanExpresionContext ctx) {
        return visit(ctx.booleanExpression());
    }

    @Override
    public ASTNode visitComparisonOperand(LatinParser.ComparisonOperandContext ctx) {
        if (ctx.numericExpression() != null)
            return visit(ctx.numericExpression());
        if (ctx.booleanLiteral() != null)
            return visit(ctx.booleanLiteral());
        if (ctx.stringExpression() != null)
            return visit(ctx.stringExpression());
        return null;
    }

    // ============================================================
    // NUMERIC EXPRESSIONS
    // ============================================================


    @Override
    public ASTNode visitAdditiveExpression(LatinParser.AdditiveExpressionContext ctx) {
        List<LatinParser.MultiplicativeExpressionContext> operands = ctx.multiplicativeExpression();
        List<LatinParser.PlusMinusExpressionContext> operators = ctx.plusMinusExpression();

        ASTNode left = visit(operands.get(0));
        for (int i = 0; i < operators.size(); i++) {
            String op = extractPlusMinusOperator(operators.get(i));
            ASTNode right = visit(operands.get(i + 1));
            left = new NodeBinaryOperation(
                    left,
                    op,
                    right,
                    ctx.getStart().getLine(),
                    ctx.getStart().getCharPositionInLine());
        }
        return left;
    }

    @Override
    public ASTNode visitMultiplicativeExpression(LatinParser.MultiplicativeExpressionContext ctx) {
        List<LatinParser.UnaryExpressionContext> operands = ctx.unaryExpression();
        List<LatinParser.MultSplitExpressionContext> operators = ctx.multSplitExpression();

        ASTNode left = visit(operands.get(0));
        for (int i = 0; i < operators.size(); i++) {
            String op = extractMultSplitOperator(operators.get(i));
            ASTNode right = visit(operands.get(i + 1));
            left = new NodeBinaryOperation(
                    left,
                    op,
                    right,
                    ctx.getStart().getLine(),
                    ctx.getStart().getCharPositionInLine());
        }
        return left;
    }

    @Override
    public ASTNode visitUnaryExpressionAddSub(LatinParser.UnaryExpressionAddSubContext ctx) {
        String op = extractAddSubOperator(ctx.addSubExpression());
        ASTNode operand = visit(ctx.unaryExpression());
        return new NodeUnaryOperation(
                op,
                operand,
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine());
    }

    @Override
    public ASTNode visitUnaryExpressionNumeric(LatinParser.UnaryExpressionNumericContext ctx) {
        return visit(ctx.primaryNumeric());
    }

    @Override
    public ASTNode visitPrimaryNumericNumericLiteral(LatinParser.PrimaryNumericNumericLiteralContext ctx) {
        return visit(ctx.numericLiteral());
    }

    @Override
    public ASTNode visitPrimaryNumericAtributeAccessExpression(
            LatinParser.PrimaryNumericAtributeAccessExpressionContext ctx) {
        NodeIdentifier base = new NodeIdentifier(
                ctx.ID().getText(),
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine());
        return buildAccessChain(base, ctx.atributeAccessExpresion());
    }

    @Override
    public ASTNode visitPrimaryNumericNumericExpression(LatinParser.PrimaryNumericNumericExpressionContext ctx) {
        return visit(ctx.numericExpression());
    }

    @Override
    public ASTNode visitNumericLiteralInteger(LatinParser.NumericLiteralIntegerContext ctx) {
        return new NodeIntegerLiteral(
                Integer.parseInt(ctx.INTEGER().getText()),
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine());
    }

    @Override
    public ASTNode visitNumericLiteralDecimal(LatinParser.NumericLiteralDecimalContext ctx) {
        return new NodeDecimalLiteral(
                Double.parseDouble(ctx.DECIMAL().getText()),
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine());
    }

    // ============================================================
    // STRING EXPRESSIONS
    // ============================================================

    @Override
    public ASTNode visitStringAdditiveExpression(LatinParser.StringAdditiveExpressionContext ctx) {
        ASTNode left = visit(ctx.stringPrimary());
        for (LatinParser.StringAdditiveItemContext itemCtx : ctx.stringAdditiveItem()) {
            ASTNode right = visit(itemCtx);
            left = new NodeBinaryOperation(
                    left,
                    "+",
                    right,
                    ctx.getStart().getLine(),
                    ctx.getStart().getCharPositionInLine());
        }
        return left;
    }

    @Override
    public ASTNode visitStringAdditiveItemStringPrimary(LatinParser.StringAdditiveItemStringPrimaryContext ctx) {
        return visit(ctx.stringPrimary());
    }

    @Override
    public ASTNode visitStringAdditiveItemNumericExpression(
            LatinParser.StringAdditiveItemNumericExpressionContext ctx) {
        return visit(ctx.numericExpression());
    }

    @Override
    public ASTNode visitStringPrimaryString(LatinParser.StringPrimaryStringContext ctx) {
        return new NodeStringLiteral(
                ctx.STRING().getText(),
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine());
    }

    @Override
    public ASTNode visitStringPrimaryChar(LatinParser.StringPrimaryCharContext ctx) {
        String text = ctx.CHAR().getText();
        char value = text.length() >= 3 ? text.charAt(1) : '\0';
        return new NodeCharLiteral(
                value,
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine());
    }

    @Override
    public ASTNode visitStringPrimaryAtributeAccessExpression(
            LatinParser.StringPrimaryAtributeAccessExpressionContext ctx) {
        NodeIdentifier base = new NodeIdentifier(
                ctx.ID().getText(),
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine());
        return buildAccessChain(base, ctx.atributeAccessExpresion());
    }

    // ============================================================
    // BOOLEAN LITERALS
    // ============================================================

    @Override
    public ASTNode visitBooleanLiteralVerum(LatinParser.BooleanLiteralVerumContext ctx) {
        return new NodeBooleanLiteral(
                true,
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine());
    }

    @Override
    public ASTNode visitBooleanLiteralFalsus(LatinParser.BooleanLiteralFalsusContext ctx) {
        return new NodeBooleanLiteral(
                false,
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine());
    }

    // ============================================================
    // Attribute access and indexing
    // ============================================================

    @Override
    public ASTNode visitAtributeAccessExpressionDitID(LatinParser.AtributeAccessExpressionDitIDContext ctx) {
        return new NodeFieldAccess(
                ctx.ID().getText(),
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine());
    }

    @Override
    public ASTNode visitAtributeAccessExpressionClaspExpression(
            LatinParser.AtributeAccessExpressionClaspExpressionContext ctx) {
        ASTNode index = visit(ctx.expression());
        return new NodeIndexAccess(
                index,
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine());
    }


    // ============================================================
    // ARRAY CREATION AND ARRAY LITERAL
    // ============================================================


    @Override
    public ASTNode visitArrayLiteral(LatinParser.ArrayLiteralContext ctx) {
        NodeArrayLiteral arrLit = new NodeArrayLiteral(
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine());
        for (LatinParser.ExpressionContext exprCtx : ctx.expression()) {
            ASTNode value = visit(exprCtx);
            if (value != null) {
                arrLit.addValue(value);
            }
        }
        return arrLit;
    }

    private static NodeLvalue asLvalue(ASTNode node) {
        return (node instanceof NodeLvalue) ? (NodeLvalue) node : null;
    }

    private static NodeBlock asBlock(ASTNode node) {
        return (node instanceof NodeBlock) ? (NodeBlock) node : null;
    }

    private static NodeBooleanExpression wrapBoolean(ASTNode node, int line, int column) {
        if (node instanceof NodeBooleanExpression) {
            return (NodeBooleanExpression) node;
        }
        return new NodeBooleanExpression(node, line, column);
    }

    // ============================================================
    // HELPER METHODS
    // ============================================================

    private String extractType(LatinParser.TypeContext ctx) {
        if (ctx == null)
            return null;
        if (ctx instanceof LatinParser.TypeNumerusContext)
            return "NUMERUS";
        if (ctx instanceof LatinParser.TypeTextumContext)
            return "TEXTUM";
        if (ctx instanceof LatinParser.TypeDecimalisContext)
            return "DECIMALIS";
        if (ctx instanceof LatinParser.TypeLitteraContext)
            return "LITTERA";
        if (ctx instanceof LatinParser.TypeIDContext)
            return ctx.getText();
        if (ctx instanceof LatinParser.TypeBoolContext)
            return "BOOL";
        return null;
    }

    private String extractRelationalOperator(LatinParser.RelationalLiteralContext ctx) {
        if (ctx == null)
            return "==";
        if (ctx instanceof LatinParser.RelationalLiteralIdenticContext)
            return "==";
        if (ctx instanceof LatinParser.RelationalLiteralDiffContext)
            return "!=";
        if (ctx instanceof LatinParser.RelationalLiteralMinorContext)
            return "<";
        if (ctx instanceof LatinParser.RelationalLiteralMajorContext)
            return ">";
        if (ctx instanceof LatinParser.RelationalLiteralMinorToContext)
            return "<=";
        if (ctx instanceof LatinParser.RelationalLiteralMajorToContext)
            return ">=";
        return "==";
    }

    private String extractPlusMinusOperator(LatinParser.PlusMinusExpressionContext ctx) {
        if (ctx == null)
            return "+";
        if (ctx instanceof LatinParser.PlusMinusExpressionPlusContext)
            return "+";
        if (ctx instanceof LatinParser.PlusMinusExpressionMinusContext)
            return "-";
        return "+";
    }

    private String extractMultSplitOperator(LatinParser.MultSplitExpressionContext ctx) {
        if (ctx == null)
            return "*";
        if (ctx instanceof LatinParser.MultSplitExpressionMultContext)
            return "*";
        if (ctx instanceof LatinParser.MultSplitExpressionSplitContext)
            return "/";
        return "*";
    }

    private String extractAddSubOperator(LatinParser.AddSubExpressionContext ctx) {
        if (ctx == null)
            return "+";
        if (ctx instanceof LatinParser.AddSubExpressionPlusContext)
            return "+";
        if (ctx instanceof LatinParser.AddSubExpressionMinusContext)
            return "-";
        if (ctx instanceof LatinParser.AddSubExpressionAddContext)
            return "+";
        if (ctx instanceof LatinParser.AddSubExpressionSubContext)
            return "-";
        return "+";
    }

    private ASTNode normalizeInitializerLiteral(ASTNode node, String rawText, int line, int column) {
        if (node instanceof NodeIntegerLiteral) {
            if ("verum".equals(rawText)) {
                return new NodeBooleanLiteral(true, line, column);
            }
            if ("falsus".equals(rawText)) {
                return new NodeBooleanLiteral(false, line, column);
            }
            if (rawText != null && rawText.length() >= 3 && rawText.startsWith("'") && rawText.endsWith("'")) {
                return new NodeCharLiteral(rawText.charAt(1), line, column);
            }
        }
        return node;
    }
}
