package com.piglatin.piglatin.domain.ast.visitor;

import com.piglatin.piglatin.domain.ast.nodes.*;
import com.piglatin.piglatin.domain.ast.nodes.NodeImport;
import com.piglatin.piglatin.domain.ast.nodes.declaration.*;
import com.piglatin.piglatin.domain.ast.nodes.lvalue.*;
import com.piglatin.piglatin.domain.ast.nodes.expression.*;
import com.piglatin.piglatin.domain.ast.nodes.instruction.*;
import com.piglatin.piglatin.domain.ast.nodes.literal.*;
import com.piglatin.piglatin.domain.ast.principal.ASTNode;
import com.piglatin.piglatin.domain.ast.principal.NodeProgram;
import com.piglatin.piglatin.infrastructure.parser.generated.LatinParser;
import com.piglatin.piglatin.infrastructure.parser.generated.LatinParserBaseVisitor;
import org.antlr.v4.runtime.tree.TerminalNode;

import java.util.ArrayList;
import java.util.List;

/**
 * ANTLR4 Visitor -> Custom AST.
 * Converts the Concrete Syntax Tree (CST) generated by ANTLR4 into the
 * Abstract Syntax Tree (AST) defined in package model.nodes.
 *
 * Each visit Context method takes a CST node and returns the equivalent AST
 * node
 */
public class ASTBuilder extends LatinParserBaseVisitor<ASTNode> {

    //* ============================================================
    //* ROOT PROGRAM
    //* ============================================================

    @Override
    public ASTNode visitProgram(LatinParser.ProgramContext ctx) {
        NodeProgram program = new NodeProgram();

        //* Imports
        if (ctx.importList() != null) {
              ASTNode imports = visit(ctx.importList());
              if (imports != null) program.setImports((List<NodeImport>) imports);
        }

        //* Global declarations
        if (ctx.globalDeclarations() != null) {
            for (LatinParser.GlobalDeclarationContext declCtx : ctx.globalDeclarations().globalDeclaration()) {
                ASTNode decl = visit(declCtx);
                if (decl instanceof NodeDeclaration) {
                    program.addGlobalDeclaration((NodeDeclaration) decl);
                }
            }
        }

        //* Main instructions
        if (ctx.mainInstructions() != null) {
            for (LatinParser.InstructionContext instCtx : ctx.mainInstructions().instruction()) {
                ASTNode inst = visit(instCtx);
                if (inst != null) {
                    program.addMainInstruction(inst);
                }
            }
        }

        return program;
    }

    @Override
    public ASTNode visitImportList(LatinParser.ImportListContext ctx){
        List<NodeImport> imports = new ArrayList<>();
        for (LatinParser.ImportStatementContext impCtx : ctx.importStatement()) {
            ASTNode imp = visit(impCtx);
            if (imp instanceof NodeImport) imports.add((NodeImport) imp);
        }
        return (ASTNode) imports;
    }

    @Override
    public ASTNode visitImportStatement(LatinParser.ImportStatementContext ctx) {
        List<String> path = new ArrayList<>();
        for (TerminalNode idCtx : ctx.ID()){
            path.add(idCtx.getText());
        }
        return new NodeImport(path, ctx.getStart().getLine(), ctx.getStart().getCharPositionInLine());
    }

    @Override
    public ASTNode visitGlobalDeclarationVariable (LatinParser.GlobalDeclarationVariableContext ctx){
        return visit(ctx.declaration());
    }

    @Override
    public ASTNode visitGlobalDeclarationArray(LatinParser.GlobalDeclarationArrayContext ctx) {
        return visit(ctx.arrayDeclaration());
    }

    @Override
    public ASTNode visitMainInstructions(LatinParser.MainInstructionsContext ctx) {
        return null;
    }

    // ============================================================
    // STATEMENTS
    // ============================================================

    @Override
    public ASTNode visitDeclaration(LatinParser.DeclarationContext ctx) {
        String id = ctx.ID().getText();
        String type = ctx.type() != null ? extractType(ctx.type()) : null;
        ASTNode initializer = ctx.expression() != null
                ? normalizeInitializerLiteral(
                        visit(ctx.expression()),
                        ctx.expression().getText(),
                        ctx.getStart().getLine(),
                        ctx.getStart().getCharPositionInLine())
                : null;

        return new NodeVariableDeclaration(
                id,
                type,
                initializer,
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine());
    }

    @Override
    public ASTNode visitArrayDeclaration(LatinParser.ArrayDeclarationContext ctx) {
        String id = ctx.ID().getText();
        ASTNode sizeExpr = visit(ctx.expression());
        String elementType = ctx.type() != null ? extractType(ctx.type()) : null;

        NodeArrayDeclaration arrDecl = new NodeArrayDeclaration(
                id,
                sizeExpr,
                elementType,
                new ArrayList<>(),
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine());

        if (ctx.arrayLiteral() != null) {
            ASTNode literal = visit(ctx.arrayLiteral());
            if (literal instanceof NodeArrayLiteral) arrDecl.setInitialValues(((NodeArrayLiteral) literal).getValues());
        }
        return arrDecl;
    }

    // ============================================================
    // INSTRUCTIONS
    // ============================================================

    @Override
    public ASTNode visitInstructionAssignment (LatinParser.InstructionAssignmentContext ctx) {
            return visit(ctx.assignment());
    }

    @Override
    public ASTNode visitInstructionRead (LatinParser.InstructionReadContext ctx) {
        return visit(ctx.readStatement());
    }

    @Override
    public ASTNode visitInstructionPrint (LatinParser.InstructionPrintContext ctx) {
        return visit(ctx.printStatement());
    }

    @Override
    public ASTNode visitInstructionIf (LatinParser.InstructionIfContext ctx) {
        return visit(ctx.ifStatement());
    }

    @Override
    public ASTNode visitInstructionWhile (LatinParser.InstructionWhileContext ctx) {
        return visit(ctx.whileStatement());
    }

    @Override
    public ASTNode visitInstructionDoWhile (LatinParser.InstructionDoWhileContext ctx) {
        return visit(ctx.doWhileStatement());
    }


    @Override
    public ASTNode visitInstructionFor (LatinParser.InstructionForContext ctx) {
        return visit(ctx.forStatement());
    }


    @Override
    public ASTNode visitInstructionJump (LatinParser.InstructionJumpContext ctx) {
        return visit(ctx.jumpStatement());
    }


    @Override
    public ASTNode visitInstructionDeclaration (LatinParser.InstructionDeclarationContext ctx) {
        return visit(ctx.declaration());
    }


    @Override
    public ASTNode visitInstructionArrayDeclaration (LatinParser.InstructionArrayDeclarationContext ctx) {
        return visit(ctx.arrayDeclaration());
    }


    @Override
    public ASTNode visitInstructionExpression (LatinParser.InstructionExpressionContext ctx) {
        return visit(ctx.expression());
    }

    @Override
    public ASTNode visitAssignment(LatinParser.AssignmentContext ctx) {
        NodeLvalue lvalue = asLvalue(visit(ctx.lvalue()));
        ASTNode expression = visit(ctx.expression());
        return new NodeAssignment(
                lvalue,
                expression,
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine());
    }

    @Override
    public ASTNode visitReadSimple(LatinParser.ReadSimpleContext ctx) {
        return new NodeRead(
                null,
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine());
    }

    @Override
    public ASTNode visitReadLvalue (LatinParser.ReadLvalueContext ctx) {
        NodeLvalue lvalue = asLvalue(visit(ctx.lvalue()));
        return new NodeRead(lvalue, ctx.getStart().getLine(), ctx.getStart().getCharPositionInLine());
    }

    @Override
    public ASTNode visitPrintStatement(LatinParser.PrintStatementContext ctx) {
        NodePrint print = new NodePrint(
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine());
        for (LatinParser.PrintItemContext itemCtx : ctx.printItem()) {
            ASTNode item = visit(itemCtx);
            if (item != null) {
                print.addPrintItem(item);
            }
        }
        return print;
    }

    @Override
    public ASTNode visitPrintString(LatinParser.PrintStringContext ctx) {
        return new NodeStringLiteral(
                ctx.STRING().getText(),
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine());
    }

    @Override
    public ASTNode visitPrintExpression(LatinParser.PrintExpressionContext ctx) {
        return visit(ctx.expression());
    }

    @Override
    public ASTNode visitIfStatement(LatinParser.IfStatementContext ctx) {

        ASTNode condition = visit(ctx.booleanExpression());
        NodeBlock thenBlock = asBlock(visit(ctx.block()));

        NodeIf nodeIf = new NodeIf(
                condition,
                thenBlock,
                new ArrayList<>(),
                null,
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine());

        // * else if clauses
        for (LatinParser.ElseIfClauseContext elseIfCtx : ctx.elseIfClause()) {

            ASTNode elseCondition = visit(ctx.booleanExpression());
            NodeBlock elseIfBlock = asBlock(visit(elseIfCtx.block()));
            nodeIf.addElseIfClause(elseCondition, elseIfBlock);
        }

        // * else clause
        if (ctx.elseClause() != null) {
            nodeIf.setElseBlock(asBlock(visit(ctx.elseClause())));
        }

        return nodeIf;
    }

    @Override
    public ASTNode visitElseIfClause(LatinParser.ElseIfClauseContext ctx) {
        return null;
    }

    @Override
    public ASTNode visitElseClause(LatinParser.ElseClauseContext ctx) {
        return visit(ctx.block());
    }

    @Override
    public ASTNode visitWhileStatement(LatinParser.WhileStatementContext ctx) {
        ASTNode condition= visit(ctx.booleanExpression());
        NodeBlock block = asBlock(visit(ctx.block()));
        return new NodeWhile(
                condition,
                block,
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine());
    }

    @Override
    public ASTNode visitDoWhileStatement(LatinParser.DoWhileStatementContext ctx) {
        NodeBlock block = asBlock(visit(ctx.block()));
        ASTNode condition = visit(ctx.booleanExpression());
        return new NodeDoWhile(
                block,
                condition,
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine());
    }

    @Override
    public ASTNode visitForStatement(LatinParser.ForStatementContext ctx) {
        ASTNode init = ctx.forInit() != null ? visit(ctx.forInit()) : null;
        ASTNode condition = ctx.booleanExpression() != null ? visit(ctx.booleanExpression()) : null;
        ASTNode update = ctx.forUpdate() != null ? visit(ctx.forUpdate()) : null;
        NodeBlock block = asBlock(visit(ctx.block()));

        return new NodeFor(
                init,
                condition,
                update,
                block,
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine());
    }

    @Override
    public ASTNode visitForInitDeclaration(LatinParser.ForInitDeclarationContext ctx) {
        String id = ctx.ID().getText();
        String type = ctx.type() != null ? extractType(ctx.type()) : null;
        ASTNode initializer = ctx.expression() != null
                ? normalizeInitializerLiteral(
                        visit(ctx.expression()),
                        ctx.expression().getText(),
                        ctx.getStart().getLine(),
                        ctx.getStart().getCharPositionInLine())
                : null;
        return new NodeVariableDeclaration(
                id,
                type,
                initializer,
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine());
    }

    @Override
    public ASTNode visitForInitAssignment(LatinParser.ForInitAssignmentContext ctx) {
        return visit(ctx.assignment());
    }

    @Override
    public ASTNode visitForInitEmpty(LatinParser.ForInitEmptyContext ctx) {
        return null;
    }

    @Override
    public ASTNode visitForUpdateExpression(LatinParser.ForUpdateExpressionContext ctx) {
        return visit(ctx.expression());
    }

    @Override
    public ASTNode visitForUpdateAssignment(LatinParser.ForUpdateAssignmentContext ctx) {
        return visit(ctx.assignment());
    }



    @Override
    public ASTNode visitJumpContinue(LatinParser.JumpContinueContext ctx) {
        return new NodeContinue(
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine());
    }

    @Override
    public ASTNode visitJumpBreak(LatinParser.JumpBreakContext ctx) {
        return new NodeBreak(
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine());
    }

    @Override
    public ASTNode visitBlock(LatinParser.BlockContext ctx) {
        NodeBlock block = new NodeBlock(
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine());
        for (LatinParser.InstructionContext instCtx : ctx.instruction()) {
            ASTNode inst = visit(instCtx);
            if (inst != null) {
                block.addInstruction(inst);
            }
        }
        return block;
    }

    // ============================================================
    // LVALUE assignable values
    // ============================================================

    @Override
    public ASTNode visitLvalue(LatinParser.LvalueContext ctx) {
        NodeLvalue lvalue = new NodeLvalue(
                ctx.ID().getText(),
                new ArrayList<>(),
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine());

        for (LatinParser.LvalueSuffixContext suffixCtx : ctx.lvalueSuffix()) {
            ASTNode suffix = visit(suffixCtx);
            if (suffix != null) {
                lvalue.addSuffix(suffix);
            }
        }

        return lvalue;
    }

    @Override
    public ASTNode visitFieldAccess(LatinParser.FieldAccessContext ctx) {
        return new NodeFieldAccess(
                null,
                ctx.ID().getText(),
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine());
    }

    @Override
    public ASTNode visitIndexAccess(LatinParser.IndexAccessContext ctx) {
        ASTNode index = visit(ctx.expression());
        return new NodeIndexAccess(
                null,
                index,
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine());
    }

    // ============================================================
    // GENERAL EXPRESSIONS
    // ============================================================

    @Override
    public ASTNode visitExprBoolean(LatinParser.ExprBooleanContext   ctx) {
        return visit(ctx.booleanExpression());
    }

    @Override
    public ASTNode visitExprNumeric(LatinParser.ExprNumericContext   ctx) {
        return visit(ctx.numericExpression());
    }

    @Override
    public ASTNode visitExprString(LatinParser.ExprStringContext   ctx) {
        return visit(ctx.stringExpression());
    }

    @Override
    public ASTNode visitExprArrayLiteral(LatinParser.ExprArrayLiteralContext ctx) {
        return visit(ctx.arrayLiteral());
    }

    @Override
    public ASTNode visitExprNewInstance(LatinParser.ExprNewInstanceContext   ctx) {
        return visit(ctx.newInstance());
    }

    // ============================================================
    // BOOLEAN EXPRESSIONS
    // ============================================================

    @Override
    public ASTNode visitBooleanOrExpression(LatinParser.BooleanOrExpressionContext ctx) {
        List<LatinParser.BooleanAndExpressionContext> operands = ctx.booleanAndExpression();
        ASTNode left = visit(operands.get(0));
        for (int i = 1; i < operands.size(); i++) {
            ASTNode right = visit(operands.get(i));
            left = new NodeBinaryOperation(
                    left,
                    "||",
                    right,
                    ctx.getStart().getLine(),
                    ctx.getStart().getCharPositionInLine());
        }
        return left;
    }

    @Override
    public ASTNode visitBooleanAndExpression(LatinParser.BooleanAndExpressionContext ctx) {
        List<LatinParser.ComparisonExpressionContext> operands = ctx.comparisonExpression();
        ASTNode left = visit(operands.get(0));
        for (int i = 1; i < operands.size(); i++) {
            ASTNode right = visit(operands.get(i));
            left = new NodeBinaryOperation(
                    left,
                    "&&",
                    right,
                    ctx.getStart().getLine(),
                    ctx.getStart().getCharPositionInLine());
        }
        return left;
    }


    //* ============================================================
    //* NEW INSTANCE
    //* ============================================================

    @Override
    public ASTNode visitNewInstance (LatinParser.NewInstanceContext  ctx) {
        String className = ctx.ID().getText();
        List<ASTNode> arguments = new ArrayList<>();

        if (ctx.argumentList() != null){
            for (LatinParser.ExpressionContext argCtx : ctx.argumentList().expression()) {
                arguments.add(visit(argCtx));
            }
        }

        return new NodeNewInstance( className, arguments, ctx.getStart().getLine(), ctx.getStart().getCharPositionInLine());
    }

    @Override
    public ASTNode visitCompNot (LatinParser.CompNotContext ctx) {
        ASTNode operand = visit (ctx.comparisonExpression());
        return new NodeUnaryOperation("!", operand, ctx.getStart().getLine(), ctx.getStart().getCharPositionInLine());
    }

    @Override
    public ASTNode visitCompCompare (LatinParser.CompCompareContext ctx) {
        if (ctx.comparisonOperand().size() == 1) return visit(ctx.comparisonOperand(0));

        ASTNode left = visit(ctx.comparisonOperand(0));
        ASTNode right = visit(ctx.comparisonOperand(1));
        String operator = extractRelationalOperator(ctx.relationalOp());

        return new NodeBinaryOperation(left, operator, right, ctx.getStart().getLine(), ctx.getStart().getCharPositionInLine());
    }

    @Override
    public ASTNode visitCompParen (LatinParser.CompParenContext ctx) {
        return visit(ctx.booleanExpression());
    }

    @Override
    public ASTNode visitCompBoolean (LatinParser.CompBooleanContext ctx) {
        return visit(ctx.booleanLiteral());
    }

    @Override
    public ASTNode visitCompString (LatinParser.CompStringContext ctx) {
        return visit(ctx.stringExpression());
    }


    // ============================================================
    // NUMERIC EXPRESSIONS
    // ============================================================


    @Override
    public ASTNode visitAdditiveExpression(LatinParser.AdditiveExpressionContext ctx) {
        List<LatinParser.MultiplicativeExpressionContext> operands = ctx.multiplicativeExpression();

        ASTNode left = visit(operands.get(0));
        for (int i = 0; i < operands.size(); i++) {
            String op = ctx.getChild(2 * i - 1).getText();
            ASTNode right = visit(operands.get(i + 1));
            left = new NodeBinaryOperation(
                    left,
                    op,
                    right,
                    ctx.getStart().getLine(),
                    ctx.getStart().getCharPositionInLine());
        }
        return left;
    }

    @Override
    public ASTNode visitMultiplicativeExpression(LatinParser.MultiplicativeExpressionContext ctx) {
        List<LatinParser.UnaryExpressionContext> operands = ctx.unaryExpression();

        ASTNode left = visit(operands.get(0));
        for (int i = 0; i < operands.size(); i++) {
            String op = ctx.getChild( 2 * i - 1 ).getText();
            ASTNode right = visit(operands.get(i + 1));
            left = new NodeBinaryOperation(
                    left,
                    op,
                    right,
                    ctx.getStart().getLine(),
                    ctx.getStart().getCharPositionInLine());
        }
        return left;
    }

    @Override
    public ASTNode visitUnaryPrefix(LatinParser.UnaryPrefixContext ctx) {
        String op = ctx.getChild(0).getText();
        ASTNode operand = visit(ctx.unaryExpression());
        return new NodeUnaryOperation(
                op,
                operand,
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine());
    }

    @Override
    public ASTNode visitUnaryPrimary(LatinParser.UnaryPrimaryContext ctx) {
        return visit(ctx.primaryNumeric());
    }

    @Override
    public ASTNode visitPrimaryNumLiteral(LatinParser.PrimaryNumLiteralContext ctx) {
        return visit(ctx.numericLiteral());
    }

    @Override
    public ASTNode visitPrimaryNumId(
            LatinParser.PrimaryNumIdContext ctx) {
       String id = ctx.ID().getText();
       NodeIdentifier base = new NodeIdentifier(id, ctx.getStart().getLine(), ctx.getStart().getCharPositionInLine());

       //* Handle postfix ++ or --
       ASTNode result = buildAccessChain(base, ctx.attributeAccess());

       //* Check for postfix increment/decrement
        if (ctx.ADD() != null) {
            return new NodeIncrementDecrement(result, "++", true,
                    ctx.getStart().getLine(), ctx.getStart().getCharPositionInLine());
        }
        if (ctx.SUB() != null) {
            return new NodeIncrementDecrement(result, "--", true,
                    ctx.getStart().getLine(), ctx.getStart().getCharPositionInLine());
        }
        return result;
    }

    @Override
    public ASTNode visitPrimaryNumParen(LatinParser.PrimaryNumParenContext ctx) {
        return visit(ctx.numericExpression());
    }

    @Override
    public ASTNode visitNumericLiteral(LatinParser.NumericLiteralContext ctx) {

        if (ctx.INTEGER() != null){
            return new NodeIntegerLiteral(
                    Integer.parseInt(ctx.INTEGER().getText()),
                    ctx.getStart().getLine(),
                    ctx.getStart().getCharPositionInLine());
        }else {
            return new NodeDecimalLiteral(
                    Double.parseDouble(ctx.DECIMAL().getText()),
                    ctx.getStart().getLine(),
                    ctx.getStart().getCharPositionInLine());
        }
    }

    // ============================================================
    // STRING EXPRESSIONS
    // ============================================================

    @Override
    public ASTNode visitStringAdditiveExpression(LatinParser.StringAdditiveExpressionContext ctx) {
        List<LatinParser.StringAdditiveItemContext> items = ctx.stringAdditiveItem();

        ASTNode left = visit(items.get(0));
        for (LatinParser.StringAdditiveItemContext itemCtx : ctx.stringAdditiveItem()) {
            ASTNode right = visit(itemCtx);
            left = new NodeBinaryOperation(
                    left,
                    "+",
                    right,
                    ctx.getStart().getLine(),
                    ctx.getStart().getCharPositionInLine());
        }
        return left;
    }

    @Override
    public ASTNode visitStringItemPrimary(LatinParser.StringItemPrimaryContext ctx) {
        return visit(ctx.stringPrimary());
    }

    @Override
    public ASTNode visitStringItemNumeric (LatinParser.StringItemNumericContext ctx) {
        return visit(ctx.numericExpression());
    }

    @Override
    public ASTNode visitStringItemBoolean (LatinParser.StringItemBooleanContext ctx) {
        return visit(ctx.booleanLiteral());
    }

    @Override
    public ASTNode visitStringPrimString (LatinParser.StringPrimStringContext ctx) {
        return new NodeStringLiteral(
                ctx.STRING().getText(),
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine());
    }

    @Override
    public ASTNode visitStringPrimChar (LatinParser.StringPrimCharContext ctx) {
        String text = ctx.CHAR().getText();
        char value = text.length() >= 3 ? text.charAt(0) : '\0';
        return new NodeCharLiteral(value, ctx.getStart().getLine(), ctx.getStart().getCharPositionInLine());
    }

    @Override
    public ASTNode visitStringPrimId (LatinParser.StringPrimIdContext ctx) {
        NodeIdentifier base = new NodeIdentifier(ctx.ID().getText(), ctx.getStart().getLine(), ctx.getStart().getCharPositionInLine());
        return buildAccessChain(base, ctx.attributeAccess());
    }

    // ============================================================
    // Attribute access and indexing
    // ============================================================

    @Override
    public ASTNode visitAttrField(LatinParser.AttrFieldContext ctx) {
        return new NodeFieldAccess(
                null,
                ctx.ID().getText(),
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine());
    }

    @Override
    public ASTNode visitAttrIndex(LatinParser.AttrIndexContext ctx) {
        ASTNode index = visit(ctx.expression());
        return new NodeIndexAccess(
                null,
                index,
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine());
    }

    @Override
    public ASTNode visitAttrCall(LatinParser.AttrCallContext ctx) {
        List<ASTNode> arguments = new ArrayList<>();
        if (ctx.argumentList() != null) {
            for (LatinParser.ExpressionContext argCtx : ctx.argumentList().expression()) {
                arguments.add(visit(argCtx));
            }
        }
        return new NodeFunctionCall(
                null,
                null,
                arguments,
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine());
    }


    // ============================================================
    // ARRAY CREATION AND ARRAY LITERAL
    // ============================================================


    @Override
    public ASTNode visitArrayLiteral(LatinParser.ArrayLiteralContext ctx) {
        NodeArrayLiteral arrLit = new NodeArrayLiteral(
                ctx.getStart().getLine(),
                ctx.getStart().getCharPositionInLine());
        for (LatinParser.ExpressionContext exprCtx : ctx.expression()) {
            ASTNode value = visit(exprCtx);
            if (value != null) {
                arrLit.addValue(value);
            }
        }
        return arrLit;
    }


    // ============================================================
    // HELPER METHODS
    // ============================================================

    private static NodeLvalue asLvalue(ASTNode node) {
        return (node instanceof NodeLvalue) ? (NodeLvalue) node : null;
    }

    private static NodeBlock asBlock(ASTNode node) {
        return (node instanceof NodeBlock) ? (NodeBlock) node : null;
    }

    private String extractType(LatinParser.TypeContext ctx) {
        return switch (ctx) {
            case LatinParser.TypeNumerusContext typeNumerusContext -> "NUMERUS";
            case LatinParser.TypeTextumContext typeTextumContext -> "TEXTUM";
            case LatinParser.TypeDecimalisContext typeDecimalisContext -> "DECIMALIS";
            case LatinParser.TypeLitteraContext typeLitteraContext -> "LITTERA";
            case LatinParser.TypeIDContext typeIDContext -> ctx.getText();
            case LatinParser.TypeBoolContext typeBoolContext -> "BOOL";
            case null, default -> null;
        };
    }

    private String extractRelationalOperator(LatinParser.RelationalOpContext ctx) {
        if (ctx == null)
            return "==";

        return switch (ctx.getText()) {
            case "!=" -> "!=";
            case "<" -> "<";
            case ">" -> ">";
            case "<=" -> "<=";
            case ">=" -> ">=";
            default -> "==";
        };
    }

    private ASTNode normalizeInitializerLiteral(ASTNode node, String rawText, int line, int column) {
        if (node instanceof NodeIntegerLiteral) {
            if ("verum".equals(rawText)) {
                return new NodeBooleanLiteral(true, line, column);
            }
            if ("falsus".equals(rawText)) {
                return new NodeBooleanLiteral(false, line, column);
            }
            if (rawText != null && rawText.length() >= 3 && rawText.startsWith("'") && rawText.endsWith("'")) {
                return new NodeCharLiteral(rawText.charAt(1), line, column);
            }
        }
        return node;
    }

    private ASTNode buildAccessChain(NodeIdentifier base, List<LatinParser.AttributeAccessContext> accesses) {
        ASTNode current = base;

        for (LatinParser.AttributeAccessContext access : accesses) {
            ASTNode accessNode = visit(access);
            if (accessNode instanceof NodeFieldAccess){
                //* When we have a field access, we need to combined it with the current node
                NodeFieldAccess fieldAccess = (NodeFieldAccess) accessNode;

                current = new NodeFieldAccess(current, fieldAccess.getFieldName(), fieldAccess.getLine(), fieldAccess.getColumn());
            } else if (accessNode instanceof NodeIndexAccess) {
                NodeIndexAccess indexAccess = (NodeIndexAccess) accessNode;
                current = new NodeIndexAccess(current, indexAccess.getIndexExpression(), indexAccess.getLine(), indexAccess.getColumn());
            } else if (accessNode instanceof NodeFunctionCall) {
                NodeFunctionCall functionCall = (NodeFunctionCall) accessNode;
                current = new NodeFunctionCall(current, functionCall.getFunctionName(), functionCall.getArguments(), functionCall.getLine(), functionCall.getColumn());
            }
        }
        return current;
    }
}
